spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: ${GOOGLE_OAUTH2_SECRET}
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            scope: profile, email
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
