spring:
  profiles:
    include: oauth

  application:
    name: recommend-contents

  server:
    port: 8080

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_APP_EMAIL}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  #Database
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/service
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  redis:
    host: localhost
    port: 6379
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/recommend_service
#    platform: postgres
#    username: admin_davidpark
#    password: admin_davidpark

  # JPA properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update

openai:
  api-key: ${OPEN_AI_KEY}
  model: gpt-3.5-turbo
logging.level:
  org.hibernate.SQL: debug